--- #YAML:1.0
name:                Test-Differences
version:             0.49_01
abstract:            Test strings and data structures and show differences if not ok
license:             ~
author:              
    - Curtis "Ovid" Poe <ovid@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
    Text::Diff:                    0.35
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
