---
abstract: 'Test strings and data structures and show differences if not ok'
author:
  - 'David Cantrell <david@cantrell.org.uk>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Differences
no_index:
  directory:
    - t
    - inc
requires:
  Capture::Tiny: 0.24
  Data::Dumper: 2.126
  Test::More: 0
  Text::Diff: 0.35
resources:
  repository: https://github.com/Ovid/Test-Differences
version: 0.61_01
